### ISSUE TITLE
Agent failure on TIMEOUT

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#184]
If the nmap process times out then `is_up` is never set in the result because we can't really determine if the host is up or not during a timeout. Unfortunately in `natlasnet.py`'s `submit_results` function, we check for that key immediately. Instead, we should be checking for `timed_out` first.

```
2019-10-17 02:33:34,555 — natlas-agent — WARNING — TIMEOUT: Nmap against 146.141.185.79 (c7aw07wwp8x21f3c)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./natlas-agent.py", line 200, in run
    response = netsrv.submit_results(result)
  File "/opt/natlas/natlas-agent/natlasnet.py", line 144, in submit_results
    if results.result['is_up'] and 'port_count' in results.result and results.result['port_count'] >= 0:
KeyError: 'is_up'
```

**Comment by 0xdade** [comment]
Closes with e3a609ff90f78d128c3f8d014d04ef3886fd344c
