### ISSUE TITLE
Server Port Closed (5000 & proxied 80)

### ISSUE THREAD

**Issue by jaredscottwilson** [natlas/natlas#227]
Got the server and client running, also nginx as proxy, however, both 80 and 5000 are returning port closed.

80/tcp   closed http
5000/tcp closed upnp

When the agent and server do run I am getting an error on the server side:
"[2019-11-07 16:03:26,807] ERROR in app: Exception on /api/submit [POST]" 

When I curl localhost 500 I get

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/search">/search</a>.  If not click the link.
```

So it seems to be "up" locally, just not allowing any external access.

**Comment by jaredscottwilson** [comment]
2019-11-07 16:18:26,427 — NetworkServices — WARNING — Expected 200, received 500
2019-11-07 16:18:26,428 — NetworkServices — ERROR — Error: Expecting value: line 1 column 1 (char 0)
2019-11-07 16:18:26,428 — NetworkServices — WARNING — Request to http://127.0.0.1:5000 failed. Waiting 128.081 seconds before retrying.

**Comment by 0xdade** [comment]
Are you running the agent on the same host as the server? My guess with the ports appearing closed is that there's probably a firewall blocking remote access to port 80. You can check firewall rules with `sudo iptables -L` or `sudo ufw status`, depending on what firewall is running. Can you post the server logs when the agent is running as well? If you're getting a 500 from the server then it's probably throwing an exception that will help us figure out what the root cause is.

**Comment by jaredscottwilson** [comment]
Absolutely! Thanks for the response.
1) Agent and Server on the same host
2) Nothing in IPTables that  would stop 80*
    * This is in Digital Ocean, so I have a DO firewall allowing SSH, HTTP, and TCP 5000 from my IP. I don't think I'd have to add something at that level for the host to talk to itself? Maybe I do?
3) Here are the logs from the server side. They repeat as the client is trying to do work.

```
[2019-11-07 20:21:03,880] ERROR in app: Exception on /api/getwork [GET]
Traceback (most recent call last):
  File "/opt/natlas/natlas-server/app/scope.py", line 94, in updateScanManager
    self.scanmanager = IPScanManager(scanrange, blacklistrange)
  File "/opt/natlas/natlas-server/app/ipscanmanager.py", line 31, in __init__
    self.rng = CyclicPRNG(self.total)
  File "/opt/natlas/natlas-server/app/cyclicprng.py", line 50, in __init__
    log('PRNG Starting Up')
  File "/opt/natlas/natlas-server/app/cyclicprng.py", line 28, in log
    with open(LOGFILE, 'a') as f:
PermissionError: [Errno 13] Permission denied: 'logs/scopemanager.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/natlas/natlas-server/app/auth/wrappers.py", line 44, in decorated_function
    return f(*args, **kwargs)
  File "/opt/natlas/natlas-server/app/api/routes.py", line 52, in getwork
    current_app.ScopeManager.update()
  File "/opt/natlas/natlas-server/app/scope.py", line 104, in update
    self.updateScanManager()
  File "/opt/natlas/natlas-server/app/scope.py", line 96, in updateScanManager
    log("Scan manager could not be instantiated because there was no scope configured.", printm=True)
  File "/opt/natlas/natlas-server/app/scope.py", line 13, in log
    with open(LOGFILE, 'a') as f:
PermissionError: [Errno 13] Permission denied: 'logs/scopemanager.log'
```

**Comment by 0xdade** [comment]
You shouldn't allow 5000 to the internet. The natlas server should bind to localhost and only be available to nginx, so you should only have port 80 exposed in this case.

Permission denied on `logs/scopemanager.log` suggests that the `logs` folder probably belongs to the root user (who ran the setup script) and that the user that the application is running as (presumably the `natlas` user?) doesn't have write access to that folder. Ensure that the `logs` folder, and all it's contents, are owned by the user that natlas is running as. The setup script creates a `natlas` user for you so that's who should be running the application. You can use the provided systemd service file to have systemd kick off the application as the natlas user via `systemctl start natlas-server`

**Comment by jaredscottwilson** [comment]
Thanks Dade - 
It's not open to the internet now. Was open for very short period to solely my IP.
I made sure the logs are assigned to natlas, along with other relevant files.
Good news and bad news. I was able to identify the permission problems, so I fixed that, now I'm getting a separate error on the server side:

```
[2019-11-08 14:38:13,247] ERROR in app: Exception on /api/submit [POST]
Traceback (most recent call last):
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/natlas/natlas-server/app/auth/wrappers.py", line 44, in decorated_function
    return f(*args, **kwargs)
  File "/opt/natlas/natlas-server/app/api/routes.py", line 94, in submit
    elif not current_app.ScopeManager.isAcceptableTarget(nmap.hosts[0].address):
IndexError: list index out of range
```

I can open this as a separate issue if wanting one

**Comment by jaredscottwilson** [comment]
UPDATE: Finally figured out the Nginx/Natlas comms - got it working (interface, results, and all). Now, I am still getting that list index out of range error, but **progress**!

**Comment by 0xdade** [comment]
Can you set `NATLAS_SAVE_FAILS` to True in your environment variables and then share the nmap output from the scans that are failing to upload? I think that is probably a separate issue but would like to see the input first before deciding if it needs to be it's own ticket.

**Comment by jaredscottwilson** [comment]
Hopped back on today to take a look at this. Oddly I'm not getting the out of range error. Seems to be working just right. Getting some 500s but that's to be expected. Thanks a ton for your support. I really love the tool.
