### ISSUE TITLE
Friendlier error when failure to bind port

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#257]
**Affecting:** 
Server

**Version:** 
96d511a6b897e9aa5f9b9cfd4a0bdb9eaebd266a

**Describe the bug**
If flask cannot bind, it throws an exception.

**To Reproduce**
1. Launch the natlas-server in one terminal
2. Try to launch natlas-server again on another terminal
3. ???
4. Error

**Expected behavior**
We should gracefully handle this error type if we can and print a friendlier message instead of dumping a stack trace. 

**Screenshots**
```
Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/cli.py", line 771, in run_command
    threaded=with_threads, ssl_context=cert)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
Loading Config from database
```

**Comment by 0xdade** [comment]
Not really relevant now because we're docker native. Failure to bind will result in a docker error message, not a natlas error message.
