### ISSUE TITLE
/api/getwork fails on new install due to empty nmap_history

### ISSUE THREAD

**Issue by fdcarl** [natlas/natlas#272]
**Affecting:** 
Server

**Version:** 
0.6.10

**Describe the bug**
On new installs w/ no data, there is an issue where the /api/getwork fails due to an issue w/ no results from nmap_history, which can never be populated since the getwork call fails.

```
[2020-06-09 02:50:30,555] ERROR in app: Exception on /api/getwork [GET]
Traceback (most recent call last):
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/natlas/natlas-server/app/auth/wrappers.py", line 44, in decorated_function
    return f(*args, **kwargs)
  File "/opt/natlas/natlas-server/app/api/routes.py", line 68, in getwork
    work = prepare_work(work)
  File "/opt/natlas/natlas-server/app/api/prepare_work.py", line 35, in prepare_work
    work['scan_id'] = get_unique_scan_id()
  File "/opt/natlas/natlas-server/app/api/prepare_work.py", line 23, in get_unique_scan_id
    count, context = current_app.elastic.get_host_by_scan_id(rand)
  File "/opt/natlas/natlas-server/app/elastic/interface.py", line 168, in get_host_by_scan_id
    return self.client.get_single_host(index='nmap_history', body=searchBody)
  File "/opt/natlas/natlas-server/app/elastic/client.py", line 77, in get_single_host
    return results['hits']['total'], results['hits']['hits'][0]['_source']
IndexError: list index out of range
```

**To Reproduce**
1. Setup completely new natlas server and agent w/ no data in ES
2. Add IP to scope
3. Run server
4. Attempt to run agent

**Expected behavior**
/api/getwork call to not fail on empty nmap_history

**Screenshots**

**Additional context**

**Comment by 0xdade** [comment]
I wasn't able to reproduce this in a new installation tonight. Can you include the following output?

**Elastic Version**
`curl http://localhost:9200/`

**Python Version**
`python --version`

If using latest, the git commit hash
`git log | head -n1`

OS Version:
`cat /etc/os-release`

**Comment by fdcarl** [comment]
`curl http://localhost:9200/
{
  "name" : "ns523054",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "t6TYSazeRhq93YkrvHSGxg",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`

`python --version
Python 3.6.9
`
`cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

As far as version, using the v0.6.10 natlas-server release (https://github.com/natlas/natlas/releases/download/v0.6.10/natlas-server-0.6.10.tgz)

**Comment by 0xdade** [comment]
0.6.10 requires elastic 6.x and I assume you originally tried to clone from main to get on latest and used that to setup elastic, which upgraded to 7.6.2 but then hit #262 and tried to roll back to an older version. 

Recommend moving back to main and installing nodejs manually and rerunning setup-server.
