### ISSUE TITLE
Opencensus Span Failure

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#311]
**Affecting:**
Server

**Version:**
c49512d 

**Describe the bug**
When executing `execute_delete_by_query` on a scan result, a key error is triggered in `self._attach_shard_span_attrs`. I suspect this likely has to do with ES6 vs ES7 (I am currently using es 7.6.2). I'm not even running opencensus sensors at the moment so this code path should definitely not be causing internal server errors.

**To Reproduce**

1. Setup to use an elastic 7.x cluster 
2. Collect some scans
3. Login as an admin
4. Visit a scan result page and attempt to delete the scan using the admin interface.
5. Scan is deleted, but causes an error afterwards

**Expected behavior**
The scan should be deleted and the application should not throw a 500.

**Logs**
```
172.18.0.1 - - [26/Jun/2020 08:50:28] "POST /admin/scans/delete/60ab2a6a40250d8c6c13e9f6d1a39e84 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/natlas/natlas-server/app/auth/wrappers.py", line 38, in decorated_function
    return f(*args, **kwargs)
  File "/opt/natlas/natlas-server/app/admin/routes.py", line 463, in delete_scan
    deleted = current_app.elastic.delete_scan(scan_id)
  File "/opt/natlas/natlas-server/app/elastic/interface.py", line 153, in delete_scan
    result = self.client.execute_delete_by_query(
  File "/opt/natlas/natlas-server/app/elastic/client.py", line 132, in execute_delete_by_query
    self._attach_shard_span_attrs(span, results)
  File "/opt/natlas/natlas-server/app/elastic/client.py", line 165, in _attach_shard_span_attrs
    span.add_attribute("es.shards.total", results["_shards"]["total"])
KeyError: '_shards'
```

The contents of `results` at the time of failure:

```
{'took': 78, 'timed_out': False, 'total': 1, 'deleted': 1, 'batches': 1, 'version_conflicts': 0, 'noops': 0, 'retries': {'bulk': 0, 'search': 0}, 'throttled_millis': 0, 'requests_per_second': -1.0, 'throttled_until_millis': 0, 'failures': []  }
```

**Comment by ajacques** [comment]
The response body for Elasticsearch 6.x and 7.x do not contain any `_shard` stats. Thus, we should not attempt to add these attributes to OpenCensus.
