### ISSUE TITLE
wrong permissions when running/starting agent first time

### ISSUE THREAD

**Issue by zer010bs** [natlas/natlas#352]
**Affecting:**
Agent

**Version:**
0.6.10

**Describe the bug**

when running the natlas-agent firs time, container dont 
start. when running docker -D run:

debug-output:

~~~

Traceback (most recent call last):
  File "/opt/natlas/natlas-agent/natlas-agent.py", line 13, in <module>
    from natlas.threadscan import ThreadScan
  File "/opt/natlas/natlas-agent/natlas/threadscan.py", line 9, in <module>
    from natlas import screenshots
  File "/opt/natlas/natlas-agent/natlas/screenshots.py", line 11, in <module>
    from natlas import utils
  File "/opt/natlas/natlas-agent/natlas/utils.py", line 8, in <module>
    utillogger = logging.get_logger("Utilities")
  File "/opt/natlas/natlas-agent/natlas/logging.py", line 34, in get_logger
    logger.addHandler(get_file_handler())
  File "/opt/natlas/natlas-agent/natlas/logging.py", line 24, in get_file_handler
    file_handler = RotatingFileHandler("logs/agent.log", maxBytes=1024 * 1024, backupCount=5)
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/natlas/natlas-agent/logs/agent.log'
~~~

**To Reproduce**

isnatll a fresh agent on a fresh VPS, using the 
install-instructions from 
https://github.com/natlas/natlas/blob/main/natlas-agent/README.md

atlas_env created

run_command:

~~~

docker -D run  --restart=no  -v $(pwd)/agent_env:/opt/natlas/natlas-agent/.env natlas/agent:0.6.10 


~~~

**Expected behavior**
A clear and concise running agent-container

**Screenshots**

**Additional context**

**Comment by 0xdade** [comment]
Thanks for opening this issue. Please try to `docker pull natlas/agent:main` and run that. I believe this issue was addressed in a commit already. You don't need to switch to `natlas/server:main` in order to use them together at this time, though I'd recommend it.

Let me know if `natlas/agent:main` fixes this issue for you.

**Comment by zer010bs** [comment]
natlas/agent:main did the trick

~~~

root@nsa-1:~/doxxer# ./agent_run.sh 
2020-07-24 17:30:58,666 — NetworkServices — INFO — Fetching natlas-services file from http://XXXXXXXXXXX
...

~~~

**Comment by 0xdade** [comment]
Thanks for the follow up! Maybe this is a sign that we should release the current version as 0.6.11. I'm in the middle of a huge agent rewrite to make it more maintainable, but it'll break backwards compatibility, so maybe I should make one more 0.6.x release before going to this for a 0.7.0 release.
