### ISSUE TITLE
Initial Start Up and Adding Initial User

### ISSUE THREAD

**Issue by testingapisname** [natlas/natlas#360]
**Affecting:**
Server: v0.6.10

**Version:**
1a9ff14

**Describe the bug**
Issues with the add user script, I am following the documentation and not sure where I am going wrong.

```
root@051750fcc321:/opt/natlas/natlas-server# ./add-user.py --email myemail@gmail.com --admin
usage: add-user.py [-h] [--admin] example@example.com
add-user.py: error: unrecognized arguments: --email
root@051750fcc321:/opt/natlas/natlas-server# 



root@051750fcc321:/opt/natlas/natlas-server# ./add-user.py --admin myemail@gmail.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./add-user.py", line 58, in <module>
    main()
  File "./add-user.py", line 28, in main
    user = User.query.filter_by(email=validemail).first()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password_hash AS user_password_hash, user.is_admin AS user_is_admin, user.results_per_page AS user_results_per_page, user.preview_length AS user_preview_length, user.result_format AS user_result_format 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?]
[parameters: ('myemail@gmail.com', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)


```
**To Reproduce**
I ran these steps from the documentation:
```
$ docker pull natlas/server:0.6.10
$ docker run -d -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:0.6.10
$ docker exec -it $(docker ps | grep natlas-server | cut -d' ' -f1) /bin/bash
root@5dd0d2d6ecdf:/opt/natlas/natlas-server# ./add-user.py --email example@example.com --admin
Sent example@example.com an invitation email via localhost

```
I pasted the errors I am getting above.

**Expected behavior**
What I expected to happen was to get a user created so I can login to the servers website.

**Screenshots**
I am not sure if this is related but I am getting a 500 internal server error on the website:
![image](https://user-images.githubusercontent.com/22276414/88628736-ff398e80-d073-11ea-9188-c5e8ac28c978.png)

I am able to get to the login page, though:
![image](https://user-images.githubusercontent.com/22276414/88628787-111b3180-d074-11ea-9129-02b210406b9e.png)

**Additional context**
Not sure where I am going wrong or what to do next. Any help would be greatly appreciated. I think this is an interesting project and would like to help if possible. Thanks!

**Comment by 0xdade** [comment]
Thanks for pointing out this issue. Please try pulling natlas/server:main and using that. Also the `natlas_ns-data` is a docker volume. I think the documentation needs to be updated and a new tagged version needs to be released, there are several unintuitive behaviors in the 0.6.10 tag.

If pulling main doesn't work, please include the new output and the (redacted) contents of the env file you are using.

**Comment by testingapisname** [comment]
So I tried pulling main and I think I am doing it right. But it seems to just be restarting and not ever getting set up properly.

```
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker pull natlas/server:main
[sudo] password for ubuntu: 
main: Pulling from natlas/server
6ec8c9369e08: Already exists 
401b5acb42e6: Already exists 
0976b24edb45: Already exists 
a338e6aafbdd: Already exists 
dd88b5c88f2e: Already exists 
079cdbffaa75: Pull complete 
a5043bfbd6f0: Pull complete 
Digest: sha256:00c206ddf1129d68e0f4e4660f14c789cef7c3caf5d3af3d8db502f507244053
Status: Downloaded newer image for natlas/server:main
docker.io/natlas/server:main
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker run -d -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:main
8aa77f541a0ed05175a5946445732c8efb4f82fbea144707ac52f66abf9cb036
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                                  PORTS               NAMES
8aa77f541a0e        natlas/server:main   "/bin/bash entrypoin…"   26 seconds ago      Restarting (3) Less than a second ago                       stupefied_rubin
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                        PORTS               NAMES
8aa77f541a0e        natlas/server:main   "/bin/bash entrypoin…"   About a minute ago   Restarting (3) 1 second ago                       stupefied_rubin
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                         PORTS               NAMES
8aa77f541a0e        natlas/server:main   "/bin/bash entrypoin…"   About a minute ago   Restarting (3) 9 seconds ago                       stupefied_rubin
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                          PORTS               NAMES
8aa77f541a0e        natlas/server:main   "/bin/bash entrypoin…"   2 minutes ago       Restarting (3) 15 seconds ago                       stupefied_rubin
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker stop 81
Error response from daemon: No such container: 81
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker stop 8a
8a
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker run -d -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:main
34facad756e202ac63cbaf7ee5933ec27e5983139decf793a6aa9f363f89383d
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
34facad756e2        natlas/server:main   "/bin/bash entrypoin…"   5 seconds ago       Up 3 seconds        0.0.0.0:5000->5000/tcp   kind_ride
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
34facad756e2        natlas/server:main   "/bin/bash entrypoin…"   19 seconds ago      Up 4 seconds        0.0.0.0:5000->5000/tcp   kind_ride
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
34facad756e2        natlas/server:main   "/bin/bash entrypoin…"   28 seconds ago      Up 1 second         0.0.0.0:5000->5000/tcp   kind_ride
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
34facad756e2        natlas/server:main   "/bin/bash entrypoin…"   30 seconds ago      Up 3 seconds        0.0.0.0:5000->5000/tcp   kind_ride
ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                        PORTS               NAMES
34facad756e2        natlas/server:main   "/bin/bash entrypoin…"   32 seconds ago      Restarting (3) 1 second ago                       kind_ride
ubuntu@ubuntu-VirtualBox:~/Natlas$ 
```

I am not able to get to the website at all using the natlas/server:main container. It is possible I am doing something wrong. I am not sure how to pull the env file because I thought that was inside the container and this gets stuck on restarting.

**Comment by 0xdade** [comment]
Do your docker run without the `-d` and you can see what it's doing. Alternatively use `docker logs kind_ride ` to see the logs output of the container, which should also show you what's happening. 

The env file needs to be mounted into the container (via this argument `$(pwd)/natlas_env:/opt/natlas/natlas-server/.env` ). It's mounting a file called natlas_env from the present working directory into the server container, which auto loads the `.env` file when it launches.

**Comment by testingapisname** [comment]
So I am not sure I created the .env file correctly but I included it here:

```
ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ sudo docker run -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:mainTraceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 228, in perform_request
    response = self.pool.urlopen(
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1e1331ae20>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/.venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/.venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/.venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/.venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/opt/natlas/natlas-server/natlas-server.py", line 26, in <module>
    raise e
  File "/opt/natlas/natlas-server/natlas-server.py", line 23, in <module>
    app = create_app(config_class=config, load_config=True)
  File "/opt/natlas/natlas-server/app/__init__.py", line 124, in create_app
    app.elastic = ElasticInterface(app.config["ELASTICSEARCH_URL"])
  File "/opt/natlas/natlas-server/app/elastic/interface.py", line 14, in __init__
    self.indices = ElasticIndices(self.client, basename)
  File "/opt/natlas/natlas-server/app/elastic/indices.py", line 19, in __init__
    self._initialize_indices()
  File "/opt/natlas/natlas-server/app/elastic/indices.py", line 28, in _initialize_indices
    self.client.initialize_index(index, mapping)
  File "/opt/natlas/natlas-server/app/elastic/client.py", line 67, in initialize_index
    if not self.es.indices.exists(index):
  File "/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/.venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 303, in exists
    return self.transport.perform_request(
  File "/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1e1331ae20>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1e1331ae20>: Failed to establish a new connection: [Errno 111] Connection refused)
[2020-07-28 07:46:54 +0000] [11] [INFO] Starting gunicorn 20.0.4
[2020-07-28 07:46:54 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
[2020-07-28 07:46:54 +0000] [11] [INFO] Using worker: sync
[2020-07-28 07:46:54 +0000] [13] [INFO] Booting worker with pid: 13
[2020-07-28 07:46:55 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 228, in perform_request
    response = self.pool.urlopen(
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f42284bc640>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/natlas/natlas-server/natlas-server.py", line 26, in <module>
    raise e
  File "/opt/natlas/natlas-server/natlas-server.py", line 23, in <module>
    app = create_app(config_class=config, load_config=True)
  File "/opt/natlas/natlas-server/app/__init__.py", line 124, in create_app
    app.elastic = ElasticInterface(app.config["ELASTICSEARCH_URL"])
  File "/opt/natlas/natlas-server/app/elastic/interface.py", line 14, in __init__
    self.indices = ElasticIndices(self.client, basename)
  File "/opt/natlas/natlas-server/app/elastic/indices.py", line 19, in __init__
    self._initialize_indices()
  File "/opt/natlas/natlas-server/app/elastic/indices.py", line 28, in _initialize_indices
    self.client.initialize_index(index, mapping)
  File "/opt/natlas/natlas-server/app/elastic/client.py", line 67, in initialize_index
    if not self.es.indices.exists(index):
  File "/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/.venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 303, in exists
    return self.transport.perform_request(
  File "/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f42284bc640>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f42284bc640>: Failed to establish a new connection: [Errno 111] Connection refused)
[2020-07-28 07:46:55 +0000] [13] [INFO] Worker exiting (pid: 13)
[2020-07-28 07:46:55 +0000] [11] [INFO] Shutting down: Master
[2020-07-28 07:46:55 +0000] [11] [INFO] Reason: Worker failed to boot.
ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ less natlas_env/.env
ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ cat natlas_env/.env 
SECRET_KEY=Y91gWepML8Bq1IqDO7MFy9LDbtuPrS3Z9Ge6TX3a
ELASTICSEARCH_URL=http://127.0.0.1.:9200
FLASK_ENV=production
ubuntu@ubuntu-VirtualBox`
```

**Comment by testingapisname** [comment]
So after fixing the .env I am still getting the same error as above. I tried it with the argument how it was by default and then by adding .env to the argument too:

ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ sudo docker run -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:main
raceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:....(ommitted the rest)
ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ sudo docker run -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env/.env:/opt/natlas/natlas-server/.env natlas/server:main
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:....(omitted the rest)
ubuntu@ubuntu-VirtualBox:~/Natlas/natlas$ cat natlas_env/.env 
SECRET_KEY=Y91gWepML8Bq1IqDO7MFy9LDbtuPrS3Z9Ge6TX3a
ELASTICSEARCH_URL=http://127.0.0.1:9200
FLASK_ENV=production

**Comment by 0xdade** [comment]
You should never publish the SECRET_KEY.

It's failing because it can't talk to elastic. From inside the container, 127.0.01:9200 isn't going to be your elastic node. You'll need to figure out the route from the container to your elastic cluster.

**Comment by testingapisname** [comment]
Yeah I wouldn't normally publish the SECRET_KEY I was just using the one from the example env file from the documentation to try and get started. 

That might be my issue then because I don't have an elastic cluster currently running so.. my bad. I assume I could just use the container from the development docker-compose.yml file:

```
version: "3.7"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic
```

**Comment by 0xdade** [comment]
I recommend the guidance that Elastic provides. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by testingapisname** [comment]
Yeah I have the docker container running now and can verify it with a curl request:
```
ubuntu@ubuntu-VirtualBox:~$ curl http://127.0.0.1:9200
{
  "name" : "elastic",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "1926nhpHR-yrulzKnreKBg",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
ubuntu@ubuntu-VirtualBox:~$ 

```
and with what you said I thought I needed to get the elastic clusters docker ip address so I did this:
```
ubuntu@ubuntu-VirtualBox:~$ sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' elastic
172.18.0.2
```
Which I then set the natlas_env file to that ip address:
```
ubuntu@ubuntu-VirtualBox:~$ cat natlas_env 
SECRET_KEY=ommitted
ELASTICSEARCH_URL=http://172.18.0.2:9200
FLASK_ENV=production
```
But when I run the natlas server container I still get the same error:

```
ubuntu@ubuntu-VirtualBox:~$ sudo docker run -p 5000:5000 --restart=always -v natlas_ns-data:/data:rw -v $(pwd)/natlas_env:/opt/natlas/natlas-server/.env natlas/server:main
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:
```
Sorry if I am doing something exceptionally dumb and I appreciate you taking the time to work on this with me.

**Comment by 0xdade** [comment]
Docker inspect the natlas server to ensure it's on the same subnet. You can also try to run the container with /bin/bash after natlas/server:main, but the containers are pretty slimmed down so a lot of tools won't be available.

I'm heading to bed but I'll check in in the morning.

**Comment by testingapisname** [comment]
That was the issue. They were not on the same subnet. After fixing that I am able to get to the login screen:
![image](https://user-images.githubusercontent.com/22276414/88643665-9825d500-d087-11ea-9bc0-4fd3524dd508.png)

But when I go into the container and try to run the ./add-user.py script I get this error:
`ubuntu@ubuntu-VirtualBox:~/Natlas$ sudo docker exec -it 6d bash
root@6da6fcb2bfd6:/opt/natlas/natlas-server# ls
Pipfile       __pycache__   add-user.py  config.py  entrypoint.sh  migrations        package.json   webpack.config.js
Pipfile.lock  add-scope.py  app          defaults   logs           natlas-server.py  tsconfig.json  yarn.lock
root@6da6fcb2bfd6:/opt/natlas/natlas-server# ./add-user.py --admin
Traceback (most recent call last):
  File "./add-user.py", line 67, in <module>
    main()
  File "./add-user.py", line 59, in main
    new_invite(email=None, admin=args.admin)
  File "./add-user.py", line 20, in new_invite
    msg = UserInvitation.deliver_invite(invite)
  File "/opt/natlas/natlas-server/app/models/user_invitation.py", line 55, in deliver_invite
    invite_url = url_for(
  File "/.venv/lib/python3.8/site-packages/flask/helpers.py", line 332, in url_for
    raise RuntimeError(
RuntimeError: Application was not able to create a URL adapter for request independent URL generation. You might be able to fix this by setting the SERVER_NAME config variable.`

I tried setting the SERVER_NAME to http://127.0.0.1:5000 in my .env 
```
SECRET_KEY=omitted
ELASTICSEARCH_URL=http://172.0.0.1:9200
FLASK_ENV=production
SERVER_NAME=http://127.0.0.1:5000
```
Reading the documentation I see:

SERVER_NAME | None | This should be set to the domain and optional port that your service will be accessed on. Do NOT include the scheme here. E.g. example.com or 10.0.0.15:5000
-- | -- | --


which makes me think I shouldn't set it to that but I was able to get this:
```

root@b81e487d47c0:/opt/natlas/natlas-server# ls
Pipfile       __pycache__   add-user.py  config.py  entrypoint.sh  migrations        package.json   webpack.config.js
Pipfile.lock  add-scope.py  app          defaults   logs           natlas-server.py  tsconfig.json  yarn.lock
root@b81e487d47c0:/opt/natlas/natlas-server# ./add-user.py --admin
Share this link: https://http://127.0.0.1:5000/auth/invite?token=ommittedd
```
But there is an issue with my webserver and it isn't loading anymore:
```

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2020-07-28 09:24:32 +0000] [11] [INFO] Starting gunicorn 20.0.4
[2020-07-28 09:24:32 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
[2020-07-28 09:24:32 +0000] [11] [INFO] Using worker: sync
[2020-07-28 09:24:32 +0000] [13] [INFO] Booting worker with pid: 13
[2020-07-28 09:27:23 +0000] [11] [CRITICAL] WORKER TIMEOUT (pid:13)
/.venv/lib/python3.8/site-packages/flask/app.py:2171: UserWarning: Current server name '127.0.0.1:5000' doesn't match configured server name 'http://127.0.0.1:5000'
  return self.url_map.bind_to_environ(
[2020-07-28 09:27:23 +0000] [13] [INFO] Worker exiting (pid: 13)
[2020-07-28 09:27:24 +0000] [22] [INFO] Booting worker with pid: 22
[2020-07-28 09:28:51 +0000] [11] [CRITICAL] WORKER TIMEOUT (pid:22)
[2020-07-28 09:28:51 +0000] [22] [INFO] Worker exiting (pid: 22)
[2020-07-28 09:28:51 +0000] [38] [INFO] Booting worker with pid: 38
```
This is what the website looks like with a server name set:
![image](https://user-images.githubusercontent.com/22276414/88647929-20a67480-d08c-11ea-8bed-0ba93fbb0424.png)

I tried the following server names:
SERVER_NAME=http://127.0.0.1:5000
SERVER_NAME=127.0.0.1:5000
SERVER_NAME=127.0.0.1

So I think I just need to figure out what I should actually set that server name variable to.

**Comment by 0xdade** [comment]
SERVER_NAME should be 127.0.0.1:5000 or localhost:5000, do not include the http:// but do include the port if its not 80. You may also need to set PREFERRED_URL_SCHEME=http since you're loading over localhost without ssl.

**Comment by testingapisname** [comment]
Was able to get the ./add-user.py to run and get logged in. Thanks for the help. 
![image](https://user-images.githubusercontent.com/22276414/88720271-35195a00-d0ea-11ea-9c17-9636e13025d5.png)


Now onto trying to get the agent connected and working!

**Comment by 0xdade** [comment]
I'll leave this open until I get the docs updated to stop recommending 0.6.10.
