### ISSUE TITLE
User Invitations failing - object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by 0xdade** [natlas/natlas#76]
User invitations are broken, it looks like we're encoding the user id with None instead of the actual user id. 
```
Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dade/natlas/natlas-server/app/auth/routes.py", line 88, in invite_user
    user = User.verify_invite_token(token)
  File "/home/dade/natlas/natlas-server/app/models.py", line 56, in verify_invite_token
    return User.query.get(id)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 924, in get
    ident, loading.load_on_pk_identity)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 985, in _get_impl
    if len(primary_key_identity) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
```

**Comment by 0xdade** [comment]
Of course, right as I file the bug report, I find the source of the problem.

`natlas-server/app/admin/routes.py:L42-44`

```
        db.session.add(newUser)
        send_user_invite_email(newUser)
        db.session.commit()
```

In this order of events, we're sending an invite email to a user that doesn't have an ID yet, and the invite token is encoding user.id, which means it's encoding a NoneType.
